---
- name: Install and configure Apache web server
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Check if systemd is available
      ansible.builtin.stat:
        path: /run/systemd/system
      register: systemd_check

    - name: Start and enable Apache2 with systemd
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: systemd_check.stat.exists

    - name: Start Apache2 without systemd (container environment)
      ansible.builtin.command: apache2ctl start
      args:
        creates: /var/run/apache2/apache2.pid
      when: not systemd_check.stat.exists

    - name: Create custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Apache Test Page</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  }
                  .container {
                      text-align: center;
                      background: white;
                      padding: 50px;
                      border-radius: 10px;
                      box-shadow: 0 10px 30px rgba(0,0,0,0.3);
                  }
                  h1 {
                      color: #333;
                      font-size: 3em;
                      margin: 0;
                  }
                  p {
                      color: #666;
                      font-size: 1.2em;
                      margin-top: 20px;
                  }
                  .success {
                      color: #4CAF50;
                      font-weight: bold;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>It works!</h1>
                  <p class="success">Apache has been successfully installed via Ansible</p>
                  <p>Your secret is {{ var1 }}</p>
                  <p>The other variable is {{ var2 }}</p>
                  <p>Server is running on {{ ansible_hostname }}</p>
                  <p>{{ ansible_distribution }} {{ ansible_distribution_version }}</p>
              </div>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reload Apache2 configuration with systemd
      ansible.builtin.service:
        name: apache2
        state: reloaded
      when: systemd_check.stat.exists

    - name: Reload Apache2 configuration without systemd
      ansible.builtin.command: apache2ctl -k graceful
      when: not systemd_check.stat.exists
      changed_when: true

    - name: Wait for Apache to be ready
      ansible.builtin.wait_for:
        port: 80
        host: 127.0.0.1
        delay: 2
        timeout: 30
        state: started

    - name: Verify Apache is responding
      ansible.builtin.uri:
        url: http://localhost/
        status_code: 200
        timeout: 5
      register: apache_check
      retries: 3
      delay: 2
      until: apache_check.status == 200

    - name: Display success message
      ansible.builtin.debug:
        msg:
          - "Apache has been successfully installed and configured!"
          - "You can access the web server at http://localhost/"
          - "or http://{{ ansible_default_ipv4.address | default('your-server-ip') }}/"
